name: 'dbt_project'
version: '1.0.0'
config-version: 2

# Use the correct profile name (matching profiles.yml)
profile: 'dbt_project'  # Changed from 'test_profile' to 'dbt_project'

model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

target-path: "target"
clean-targets:
  - "target"
  - "dbt_packages"

models:
  dbt_project:
    example:
      +materialized: view
