test_profile:
  target: dev
  outputs:
    dev:
      type: sqlserver
      driver: "ODBC Driver 18 for SQL Server"
      host: localhost
      port: 1433
      user: "sa"
      password: "gotoz@123"
      database: "master"
      schema: "dbo"
      threads: 1
      encrypted: false
      trust_cert: true