dbt_project:
  target: dev
  outputs:
    dev:
      type: sqlserver
      driver: "ODBC Driver 18 for SQL Server"
      host: 192.168.29.250
      port: 1433
      user: Sales_Login
      password: gotoz
      database: Sales_DB
      schema: dbo
      threads: 1
      encrypted: false
      trust_cert: true