name: Development CI For dbt

on:
  push:
    branches:
      - 'main'

jobs:
  deploy:
    runs-on: ubuntu-latest

    environment: development  

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Echo Checkout Status
        run: |
          echo "Repository checkout completed"
          echo "Current directory: ${{ github.workspace }}"
          echo "Git ref: ${{ github.ref }}"

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dbt
        run: |
          python -m pip install --upgrade pip
          pip install dbt-core dbt-postgres 

      - name: dbt Dependencies
        run: dbt deps

      - name: dbt Compile
        run: dbt compile

      - name: Run dbt Tests
        run: dbt test

      - name: Build dbt Models
        run: dbt build --target development

      - name: Generate dbt Docs
        run: dbt docs generate
