name: Development CI For dbt

on:
  push:
    branches:
      - 'feature/*' 

jobs:
  development:
    runs-on: ubuntu-latest
    environment: development  

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0  

      - name: Echo Checkout Status
        run: |
          echo "Repository checkout completed"
          echo "Current directory: ${{ github.workspace }}"
          echo "Git ref: ${{ github.ref }}"
          ls -la  # List files to verify structure

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dbt with Microsoft SQL Server Adapter
        run: |
          python -m pip install --upgrade pip
          pip install dbt-core dbt-mssql

      - name: Verify dbt Installation
        run: dbt --version

      - name: Setup dbt Profile (Load from Secrets)
        run: |
          mkdir -p ~/.dbt
          echo "${{ secrets.PROFILES_YML }}" > ~/.dbt/profiles.yml
          # Remove debugging step for production
          # cat ~/.dbt/profiles.yml  

      - name: Change to dbt Project Directory
        run: |
          cd dbt_project
          echo "Current directory: $(pwd)"
          ls -la  # List files to confirm dbt_project.yml exists

      - name: dbt Dependencies
        run: cd dbt_project && dbt deps

      # - name: Run dbt Tests
      #   run: cd dbt_project && dbt test

      # - name: Build dbt Models
      #   id: dbt_build
      #   run: cd dbt_project && dbt build --target development
        
      - name: Merge to Feature Branch
        if: success()  # Only run if all previous steps succeeded
        run: |
          git config --global user.name 'GitHub Actions'
          git config --global user.email 'github-actions@github.com'
          
          # Extract the branch name without 'refs/heads/' prefix
          BRANCH_NAME=${GITHUB_REF#refs/heads/}
          echo "Current branch is $BRANCH_NAME"
          
          echo "Build successful! Changes are already in the $BRANCH_NAME branch."

  docker-build:
    needs: development  
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build Docker Image
        run: |
          docker build -t my-dbt-app:latest .
          docker tag my-dbt-app:latest ${{ secrets.DOCKER_USERNAME }}/my-dbt-app:latest

      - name: Push Docker Image
        run: |
          docker push ${{ secrets.DOCKER_USERNAME }}/my-dbt-app:latest