name: Development CI For dbt

on:
  push:
    branches:
      - 'main'  # Runs on push to 'main' branch

jobs:
  deploy:
    runs-on: ubuntu-latest

    environment: development  

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Echo Checkout Status
        run: |
          echo "Repository checkout completed"
          echo "Current directory: ${{ github.workspace }}"
          echo "Git ref: ${{ github.ref }}"
          ls -la  # List files to verify structure

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dbt with Microsoft SQL Server Adapter
        run: |
          python -m pip install --upgrade pip
          pip install dbt-core dbt-mssql

      - name: Verify dbt Installation
        run: dbt --version

      - name: Setup dbt Profile (Load from Secrets)
        run: |
          mkdir -p ~/.dbt
          echo "${{ secrets.PROFILES_YML }}" > ~/.dbt/profiles.yml
          echo "profiles.yml configured for development"
          cat ~/.dbt/profiles.yml  # Debugging step (remove in production)

      - name: Validate dbt Project Structure
        run: |
          ls -la dbt_project  # Check if dbt_project.yml is present

      - name: dbt-version
        uses: mwhitaker/dbt-action@v1.6.3
        with:
          dbt_command: "dbt --version"
          dbt_project_folder: "dbt_project"

      - name: dbt-deps
        uses: mwhitaker/dbt-action@v1.6.3
        with:
          dbt_command: "dbt deps"
          dbt_project_folder: "dbt_project"

      - name: dbt-run
        uses: mwhitaker/dbt-action@v1.6.3
        with:
          dbt_command: "dbt run"
          dbt_project_folder: "dbt_project"

      - name: dbt-test
        uses: mwhitaker/dbt-action@v1.6.3
        with:
          dbt_command: "dbt test"
          dbt_project_folder: "dbt_project"
